Fix for translations
easydigitaldownloads/edd-terms-per-product pull request #5
Opened 2017-03-03 15:21 UTC by garubi

1. Enclosed the "Agree to terms" string in _e() function
2. Changed some _e() to honor the (maybe) changed edd_label (use edd_get_label_singular() )

2017-03-21 09:13 UTC, garubi commented
Any news on this?

2021-03-23 18:28 UTC, robincornett requested changes

2021-03-23 18:28 UTC, robincornett commented on edd-terms-per-product.php
> +			<strong><?php printf( __( '%s Terms of Use:', 'edd-terms-per-product' ), edd_get_label_singular() ); ?></strong>
```suggestion
			<strong><?php printf( esc_html__( '%s Terms of Use:', 'edd-terms-per-product' ), esc_html( edd_get_label_singular() ) ); ?></strong>
```

2021-03-23 18:28 UTC, robincornett commented on edd-terms-per-product.php
> +			<label for="edd_download_terms"><?php printf( __( 'Enter the terms of use for this %s:', 'edd-terms-per-product' ), edd_get_label_singular() ); ?></label>
```suggestion
			<label for="edd_download_terms"><?php printf( esc_html__( 'Enter the terms of use for this %s:', 'edd-terms-per-product' ), edd_get_label_singular() ); ?></label>
```

2021-03-23 18:28 UTC, robincornett commented on edd-terms-per-product.php
> +						<a href="#edd_<?php echo $item['id']; ?>_terms" class="edd_per_product_terms_links"><?php printf( __( 'Show Terms For %s', 'edd-terms-per-product' ), get_post_field( 'post_title', $item['id'] )
```suggestion
						<a href="#edd_<?php echo $item['id']; ?>_terms" class="edd_per_product_terms_links"><?php printf( esc_html__( 'Show Terms For %s', 'edd-terms-per-product' ), esc_html( get_post_field( 'post_title', $item['id'] ) ) ); ?></a>
```

2021-03-23 18:28 UTC, robincornett commented on edd-terms-per-product.php
> +						<a href="#edd_<?php echo $item['id']; ?>_terms" class="edd_per_product_terms_links" style="display:none;"><?php _e( 'Hide Terms', 'edd-terms-per-product' ); ?></a>
```suggestion
						<a href="#edd_<?php echo $item['id']; ?>_terms" class="edd_per_product_terms_links" style="display:none;"><?php esc_html_e( 'Hide Terms', 'edd-terms-per-product' ); ?></a>
```

2021-03-23 18:28 UTC, robincornett commented on edd-terms-per-product.php
> +					<label for="edd_agree_to_terms_<?php echo $item['id']; ?>"><?php _e( 'Agree to Terms', 'edd-terms-per-product' ); ?></label>
```suggestion
					<label for="edd_agree_to_terms_<?php echo $item['id']; ?>"><?php esc_html_e( 'Agree to Terms', 'edd-terms-per-product' ); ?></label>
```

2021-03-24 10:27 UTC, ashleyfae approved these changes

2021-03-24 12:08 UTC, robincornett approved these changes

2021-03-24 12:44 UTC, merged